spring.application.name=sensor-service
server.port=8081

# Configuración de R2DBC (Ejemplo con MySQL)
# spring.r2dbc.url=r2dbc:mysql://localhost:3306/biosense
# spring.r2dbc.username=root
# spring.r2dbc.password=root
