spring.application.name=sensor-service
server.port=${PORT:8081}

# R2DBC Configuration (Prioriza variables de Railway, si no usa localhost)
spring.r2dbc.url=${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5432/biosense}
spring.r2dbc.username=${SPRING_R2DBC_USERNAME:postgres}
spring.r2dbc.password=${SPRING_R2DBC_PASSWORD:''}

# Pool de conexiones para producción
spring.r2dbc.pool.enabled=true
spring.r2dbc.pool.initial-size=2
spring.r2dbc.pool.max-size=10

# Inicialización de base de datos
spring.sql.init.mode=always
