spring.application.name=identity-service
server.port=8082

# JWT Configuration
jjwt.secret=${JJWT_SECRET}
jjwt.expiration=86400

# R2DBC Configuration para Producción (Railway)
spring.r2dbc.url=${SPRING_R2DBC_URL}
spring.r2dbc.username=${SPRING_R2DBC_USERNAME}
spring.r2dbc.password=${SPRING_R2DBC_PASSWORD}

# Configuración para que cree las tablas automáticamente al conectar
spring.sql.init.mode=always
